name: Build Jekyll

# Controls when the workflow will run
on:
  push:
    branches:
      - 'v3.[0-9]+.x'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    uses: altbdoor/jekyll-exe-2/.github/workflows/base.yml@master
