name: Build Jekyll

# Controls when the workflow will run
on:
  push:
    branches:
      - 'v3.[0-9]+.x'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - id: dotenv
        uses: falti/dotenv-action@v0.2.7
        with:
          log-variables: true
          path: build-vars.env

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.1
          bundler: none

      - name: build
        shell: bash
        run: |
          gem sources --add https://rubygems.org
          echo 'gem: --no-document' >> ~/.gemrc
          gem install ${{ steps.dotenv.outputs.GEM_INIT_DEPENDENCY }}

          curl -OL 'https://github.com/altbdoor/jekyll-exe/raw/master/build.sh'
          ./build.sh "${{ steps.dotenv.outputs.JEKYLL_VERSION }}" "${{ steps.dotenv.outputs.BUILD_INJECT_DEPS }}" "${{ steps.dotenv.outputs.BUILD_BUNDLER_DEPS }}"

          gem list --local > gem_list.log

      - uses: actions/upload-artifact@v2
        with:
          name: jekyll-v${{ steps.dotenv.outputs.JEKYLL_VERSION }}
          path: |
            jekyll.exe
            ocra.log
            release.log
            gem_list.log
